name: Customize Resume
on:
  push:
    branches:
      - 'custom-**'
jobs:
  build:
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        node-version: [21]
    steps:
    - uses: actions/checkout@v3
    - uses: pnpm/action-setup@v2
      with:
        version: 8
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'pnpm'
    - name: Install html to pdf converter
      run: sudo apt-get install xvfb libfontconfig wkhtmltopdf
    - name: Install node dependencies
      run: pnpm install
    - name: Install template node dependencies
      run: cd theme && pnpm install
    - name: Build resumes
      run: pnpm run build
    - name: Archive production artifacts
      id: pdf-upload-step
      uses: actions/upload-artifact@v4
      with:
        name: will-weaver-resume.pdf
        path: output/will-weaver-resume.pdf
    - name: Output pdf url in PR
      uses: actions/github-script@v6
      with:
        github-token: ${{secrets.GITHUB_TOKEN}}
        script: |
          github.issues.createComment({
            issue_number: context.issue.number,
            owner: context.repo.owner,
            repo: context.repo.repo,
            body: 'Zip of pdf can be found at ${{ steps.artifact-upload-step.outputs.artifact-url }}'
          })