name: Generate Suggestions
on:
  push:
    branches:
      # - 'custom-**'
      - 'chatgpt-feedback'
jobs:
  build:
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        node-version: [21]
    steps:
      - uses: actions/checkout@v4
      - name: Debug
        run: |
          echo '' >> $GITHUB_ENV
      - id: read_resume
        run: |
          echo 'RESUME_JSON<<EOF' >> $GITHUB_ENV
          cat ./resume.json >> $GITHUB_ENV
          echo 'EOF' >> $GITHUB_ENV
      # - run: |
      #     echo "${{toJSON(fromJson(env.RESUME_JSON).basics.summary)}}"
      # - run: 
      #     echo "${{toJSON(fromJson(env.RESUME_JSON).skills)}}"
      # - name: Get ChatGPT completion
      #   id: chatgpt
      #   uses: cahaseler/openai-chatgpt-action@v1
      #   with:
      #     apiKey: ${{ secrets.OPENAI_API_KEY }}
      #     prompt: 'Act as a resume expert. Please generate a resume summary based on the included summary. Tailor it for the job description found at ${{env.JD_URL}}'
      #     input: 'put whatever you want in here'
      #     model: 'gpt-4'
      #     temperature: 1
      #     max_tokens: 200
      # - name: DEBUG
      #   run: |
      #     echo ${{join(steps.chatgpt.outputs.*, '\n')}}
      # - name: Add outputs to PR
      #   uses: mshick/add-pr-comment@v2
      #   with:
      #     message: |
      #       ${{join(steps.chatgpt.outputs.*, '\n')}}